import os
import re
from datetime import date
import psycopg
from psycopg.rows import dict_row
from functools import wraps

from flask import Flask, request, redirect, render_template_string, session, flash
from flask_wtf.csrf import CSRFProtect
from werkzeug.security import generate_password_hash, check_password_hash


app = Flask("Kawaii")

# Gerçek sunucuda SECRET_KEY'i ortam değişkeninden ver.
app.config["SECRET_KEY"] = os.environ.get(
    "SECRET_KEY",
    "dev-only-change-this-key"
)

app.config["SESSION_COOKIE_HTTPONLY"] = True
app.config["SESSION_COOKIE_SAMESITE"] = "Lax"

# HTTPS kullanınca 1 yap:
app.config["SESSION_COOKIE_SECURE"] = (
    os.environ.get("HTTPS", "0") == "1"
)

csrf = CSRFProtect(app)

# PostgreSQL bağlantısı.
# Pydroid'da ortam değişkeni DATABASE_URL olarak ayarlanabilir.
# Örnek:
# postgresql://kullanici:sifre@host:5432/veritabani
DATABASE_URL = os.environ.get("DATABASE_URL")

if not DATABASE_URL:
    raise RuntimeError(
        "DATABASE_URL ortam değişkeni ayarlanmadı."
    )


# -------------------------
# DATABASE
# -------------------------

def get_db():
    return psycopg.connect(
        DATABASE_URL,
        row_factory=dict_row
    )


def init_db():
    conn = get_db()

    conn.execute("""
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            password_hash TEXT NOT NULL
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS habits (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id INTEGER NOT NULL,
            name TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (user_id)
                REFERENCES users(id)
                ON DELETE CASCADE
        )
    """)

    conn.execute("""
        CREATE TABLE IF NOT EXISTS completions (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            habit_id INTEGER NOT NULL,
            day TEXT NOT NULL,
            UNIQUE(habit_id, day),
            FOREIGN KEY (habit_id)
                REFERENCES habits(id)
                ON DELETE CASCADE
        )
    """)

    conn.commit()
    conn.close()


# -------------------------
# AUTH
# -------------------------

def login_required(view):
    @wraps(view)
    def wrapped(*args, **kwargs):

        if "user_id" not in session:
            return redirect("/login")

        return view(*args, **kwargs)

    return wrapped


def current_user():

    if "user_id" not in session:
        return None

    conn = get_db()

    user = conn.execute(
        """
        SELECT id, username
        FROM users
        WHERE id=%s
        """,
        (session["user_id"],)
    ).fetchone()

    conn.close()

    return user


# -------------------------
# STATS
# -------------------------

def calculate_streak(conn, habit_id):

    rows = conn.execute(
        """
        SELECT day
        FROM completions
        WHERE habit_id=%s
        ORDER BY day DESC
        """,
        (habit_id,)
    ).fetchall()

    completed_days = {
        row["day"]
        for row in rows
    }

    if not completed_days:
        return 0

    current = date.today()

    # Bugün yapılmadıysa dün üzerinden seri devam edebilir.
    if str(current) not in completed_days:
        current = date.fromordinal(
            current.toordinal() - 1
        )

    streak = 0

    while str(current) in completed_days:

        streak += 1

        current = date.fromordinal(
            current.toordinal() - 1
        )

    return streak


def get_longest_streak(conn, habit_id):

    rows = conn.execute(
        """
        SELECT day
        FROM completions
        WHERE habit_id=%s
        ORDER BY day ASC
        """,
        (habit_id,)
    ).fetchall()

    longest = 0
    current_streak = 0
    previous = None

    for row in rows:

        day = date.fromisoformat(row["day"])

        if (
            previous is not None
            and (day - previous).days == 1
        ):
            current_streak += 1
        else:
            current_streak = 1

        longest = max(
            longest,
            current_streak
        )

        previous = day

    return longest


# -------------------------
# BASE HTML
# -------------------------

BASE_HTML = """
<!DOCTYPE html>

<html lang="tr">

<head>

<meta charset="UTF-8">

<meta
    name="viewport"
    content="width=device-width, initial-scale=1.0"
>

<title>{{ title }}</title>

<style>

body {
    font-family: Arial, sans-serif;
    background: #f4f5f7;
    margin: 0;
    padding: 20px;
}

.container {
    max-width: 600px;
    margin: auto;
}

.card {
    background: white;
    padding: 18px;
    margin: 12px 0;
    border-radius: 15px;
    box-shadow: 0 3px 10px #0001;
}

input {
    width: 100%;
    box-sizing: border-box;
    padding: 12px;
    margin: 6px 0 12px;

    border: 1px solid #ddd;
    border-radius: 10px;
}

button,
.button {

    border: none;
    border-radius: 10px;

    padding: 10px 15px;

    cursor: pointer;

    text-decoration: none;

    display: inline-block;
}

.add {
    background: #222;
    color: white;
}

.done {
    background: #eddeff;
}

.delete {
    background: #f3f3f3;
}

.nav {

    display: flex;

    justify-content: space-between;

    margin-bottom: 15px;
}

.error {

    background: #ffe1e1;

    padding: 10px;

    border-radius: 10px;
}

.success {

    background: #e1ffe8;

    padding: 10px;

    border-radius: 10px;
}

</style>

</head>

<body>

<div class="container">

<div class="nav">

{% if session.get("user_id") %}

<span>
👋 {{ user["username"] }}
</span>

<span>

<a class="button" href="/">
Ana Sayfa
</a>

<a class="button" href="/stats">
İstatistik
</a>

<a class="button" href="/logout">
Çıkış
</a>

</span>

{% endif %}

</div>


{% with messages = get_flashed_messages(with_categories=true) %}

    {% for category, message in messages %}

        <div class="{{ category }}">
            {{ message }}
        </div>

    {% endfor %}

{% endwith %}


{{ content|safe }}

</div>

</body>

</html>
"""


# -------------------------
# HOME
# -------------------------

HOME_HTML = """

<h1>☘︎ Alışkanlık Takibi</h1>

<div class="card">

<form action="/add" method="post">

<input
    type="hidden"
    name="csrf_token"
    value="{{ csrf_token() }}"
>

<input
    name="name"
    maxlength="100"
    placeholder="Yeni alışkanlık..."
    required
>

<button
    class="add"
    type="submit"
>
Ekle
</button>

</form>

</div>


{% for habit in habits %}

<div class="card">

<h2>
{{ habit["name"] }}
</h2>

<p>
🔥 Seri: {{ habit["streak"] }} gün
</p>


{% if habit["completed"] %}

<p>
✅ Bugün tamamlandı!
</p>

<form
    action="/toggle/{{ habit['id'] }}"
    method="post"
>

<input
    type="hidden"
    name="csrf_token"
    value="{{ csrf_token() }}"
>

<button type="submit">
↩️ Geri al
</button>

</form>

{% else %}

<p>
⬜ Bugün henüz yapılmadı
</p>

<form
    action="/toggle/{{ habit['id'] }}"
    method="post"
>

<input
    type="hidden"
    name="csrf_token"
    value="{{ csrf_token() }}"
>

<button
    class="done"
    type="submit"
>
✓ Tamamlandı
</button>

</form>

{% endif %}


<br>


<form
    action="/delete/{{ habit['id'] }}"
    method="post"
>

<input
    type="hidden"
    name="csrf_token"
    value="{{ csrf_token() }}"
>

<button
    class="delete"
    type="submit"
>
🗑️ Sil
</button>

</form>


</div>

{% else %}

<div class="card">

Henüz alışkanlık eklemedin.

</div>

{% endfor %}

"""


# -------------------------
# LOGIN
# -------------------------

LOGIN_HTML = """

<h1>🔐 Giriş</h1>

<div class="card">

<form method="post">

<input
    type="hidden"
    name="csrf_token"
    value="{{ csrf_token() }}"
>

<label>
Kullanıcı adı
</label>

<input
    name="username"
    maxlength="30"
    required
>


<label>
Şifre
</label>

<input
    type="password"
    name="password"
    required
>


<button
    class="add"
    type="submit"
>
Giriş yap
</button>

</form>


<p>
Hesabın yok mu?

<a href="/register">
Kayıt ol
</a>

</p>

</div>

"""


# -------------------------
# REGISTER
# -------------------------

REGISTER_HTML = """

<h1>📝 Kayıt Ol</h1>

<div class="card">

<form method="post">

<input
    type="hidden"
    name="csrf_token"
    value="{{ csrf_token() }}"
>


<label>
Kullanıcı adı
</label>

<input
    name="username"
    maxlength="30"
    required
>

<small>
3-30 karakter; harf, rakam ve _ kullanılabilir.
</small>


<label>
Şifre
</label>

<input
    type="password"
    name="password"
    minlength="8"
    required
>


<button
    class="add"
    type="submit"
>
Kayıt ol
</button>

</form>


<p>

Zaten hesabın var mı?

<a href="/login">
Giriş yap
</a>

</p>

</div>

"""


# -------------------------
# STATS HTML
# -------------------------

STATS_HTML = """

<h1>📊 İstatistikler</h1>


{% for habit in habits %}

<div class="card">

<h2>
{{ habit["name"] }}
</h2>

<p>
Toplam tamamlanan gün:
<b>{{ habit["total"] }}</b>
</p>

<p>
Mevcut seri:
<b>{{ habit["streak"] }} gün</b>
</p>

<p>
En uzun seri:
<b>{{ habit["longest"] }} gün</b>
</p>

</div>

{% else %}

<div class="card">

Henüz istatistik bulunmuyor.

</div>

{% endfor %}

"""


# -------------------------
# PAGE HELPER
# -------------------------

def page(template, title, **kwargs):

    user = current_user()

    content = render_template_string(
        template,
        **kwargs
    )

    return render_template_string(
        BASE_HTML,
        title=title,
        content=content,
        user=user
    )


# -------------------------
# HOME ROUTE
# -------------------------

@app.route("/")
@login_required
def home():

    conn = get_db()

    user_id = session["user_id"]

    habits = conn.execute(
        """
        SELECT id, name
        FROM habits
        WHERE user_id=%s
        ORDER BY id DESC
        """,
        (user_id,)
    ).fetchall()

    result = []

    today = str(date.today())

    for habit in habits:

        completed = conn.execute(
            """
            SELECT 1
            FROM completions
            WHERE habit_id=%s AND day=%s
            """,
            (habit["id"], today)
        ).fetchone()

        result.append({
            "id": habit["id"],
            "name": habit["name"],
            "completed": completed is not None,
            "streak": calculate_streak(
                conn,
                habit["id"]
            )
        })

    conn.close()

    return page(
        HOME_HTML,
        "Alışkanlık Takibi",
        habits=result
    )


# -------------------------
# REGISTER
# -------------------------

@app.route("/register", methods=["GET", "POST"])
def register():

    if request.method == "POST":

        username = request.form.get(
            "username",
            ""
        ).strip()

        password = request.form.get(
            "password",
            ""
        )


        # Kullanıcı adı kontrolü
        if not re.fullmatch(
            r"[A-Za-z0-9_]{3,30}",
            username
        ):

            flash(
                "Kullanıcı adı 3-30 karakter olmalı ve sadece harf, rakam ve _ içermeli.",
                "error"
            )

            return redirect("/register")


        # Şifre uzunluğu
        if len(password) < 8:

            flash(
                "Şifre en az 8 karakter olmalı.",
                "error"
            )

            return redirect("/register")


        # Şifreyi düz metin olarak kaydetmiyoruz.
        password_hash = generate_password_hash(
            password
        )


        conn = get_db()

        try:

            cursor = conn.execute(
                """
                INSERT INTO users
                (username, password_hash)
                VALUES (%s, %s)
                RETURNING id
                """,
                (
                    username,
                    password_hash
                )
            )

            conn.commit()

            session.clear()

            session["user_id"] = cursor.fetchone()["id"]

        except psycopg.errors.UniqueViolation:

            conn.close()

            flash(
                "Bu kullanıcı adı zaten kullanılıyor.",
                "error"
            )

            return redirect("/register")

        conn.close()

        return redirect("/")


    return page(
        REGISTER_HTML,
        "Kayıt Ol"
    )


# -------------------------
# LOGIN
# -------------------------

@app.route("/login", methods=["GET", "POST"])
def login():

    if request.method == "POST":

        username = request.form.get(
            "username",
            ""
        ).strip()

        password = request.form.get(
            "password",
            ""
        )


        conn = get_db()

        user = conn.execute(
            """
            SELECT id, username, password_hash
            FROM users
            WHERE username=%s
            """,
            (username,)
        ).fetchone()

        conn.close()


        if (
            user
            and check_password_hash(
                user["password_hash"],
                password
            )
        ):

            # Session fixation'a karşı eski session temizleniyor.
            session.clear()

            session["user_id"] = user["id"]

            return redirect("/")


        flash(
            "Kullanıcı adı veya şifre hatalı.",
            "error"
        )


    return page(
        LOGIN_HTML,
        "Giriş"
    )


# -------------------------
# LOGOUT
# -------------------------

@app.route("/logout")
def logout():

    session.clear()

    return redirect("/login")


# -------------------------
# ADD HABIT
# -------------------------

@app.route("/add", methods=["POST"])
@login_required
def add():

    name = request.form.get(
        "name",
        ""
    ).strip()


    if not name:

        flash(
            "Alışkanlık adı boş olamaz.",
            "error"
        )

        return redirect("/")


    if len(name) > 100:

        flash(
            "Alışkanlık adı en fazla 100 karakter olabilir.",
            "error"
        )

        return redirect("/")


    conn = get_db()

    conn.execute(
        """
        INSERT INTO habits
        (user_id, name)
        VALUES (%s, %s)
        """,
        (
            session["user_id"],
            name
        )
    )

    conn.commit()

    conn.close()

    return redirect("/")


# -------------------------
# TOGGLE
# -------------------------

@app.route("/toggle/<int:id>", methods=["POST"])
@login_required
def toggle(id):

    conn = get_db()

    user_id = session["user_id"]

    today = str(date.today())


    # IDOR koruması:
    # Habit hem ID'ye hem de mevcut kullanıcıya ait olmalı.
    habit = conn.execute(
        """
        SELECT id
        FROM habits
        WHERE id=%s AND user_id=%s
        """,
        (
            id,
            user_id
        )
    ).fetchone()


    if habit is None:

        conn.close()

        return redirect("/")


    completed = conn.execute(
        """
        SELECT id
        FROM completions
        WHERE habit_id=%s AND day=%s
        """,
        (
            id,
            today
        )
    ).fetchone()


    if completed:

        conn.execute(
            """
            DELETE FROM completions
            WHERE habit_id=%s AND day=%s
            """,
            (
                id,
                today
            )
        )

    else:

        conn.execute(
            """
            INSERT INTO completions
            (habit_id, day)
            VALUES (%s, %s)
            """,
            (
                id,
                today
            )
        )


    conn.commit()

    conn.close()

    return redirect("/")


# -------------------------
# DELETE
# -------------------------

@app.route("/delete/<int:id>", methods=["POST"])
@login_required
def delete(id):

    conn = get_db()

    # Sadece kendi alışkanlığını silebilir.
    conn.execute(
        """
        DELETE FROM habits
        WHERE id=%s AND user_id=%s
        """,
        (
            id,
            session["user_id"]
        )
    )

    conn.commit()

    conn.close()

    return redirect("/")


# -------------------------
# STATS
# -------------------------

@app.route("/stats")
@login_required
def stats():

    conn = get_db()

    habits = conn.execute(
        """
        SELECT id, name
        FROM habits
        WHERE user_id=%s
        ORDER BY id DESC
        """,
        (session["user_id"],)
    ).fetchall()


    result = []


    for habit in habits:

        total = conn.execute(
            """
            SELECT COUNT(*)
            FROM completions
            WHERE habit_id=%s
            """,
            (habit["id"],)
        ).fetchone()["count"]


        result.append({
            "name": habit["name"],
            "total": total,
            "streak": calculate_streak(
                conn,
                habit["id"]
            ),
            "longest": get_longest_streak(
                conn,
                habit["id"]
            )
        })


    conn.close()


    return page(
        STATS_HTML,
        "İstatistikler",
        habits=result
    )


# -------------------------
# START
# -------------------------

if __name__ == "__main__":

    init_db()

    # Public sunucuda debug=True kullanma.
    app.run(
        host="0.0.0.0",
        port=8080,
        debug=False
    )